version: '3'
services:
  atm-manager:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

